# Generated by Django 4.2.4 on 2023-09-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0002_remove_userpage_name_userpage_fname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPage',
        ),
    ]
