# Generated by Django 4.2.4 on 2023-09-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='score',
            field=models.IntegerField(blank=True, default=80, max_length=100, null=True),
        ),
    ]
