# Generated by Django 4.2.4 on 2023-09-07 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0006_alter_skill_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='score',
            field=models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
