# Generated by Django 4.2.4 on 2023-09-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0008_contactprofile_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='certificate/'),
        ),
    ]
