# Generated by Django 4.2.4 on 2023-09-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0009_certificate_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='images',
            field=models.ImageField(blank=True, default='certificate/work-img.jpg', null=True, upload_to='certificate/'),
        ),
    ]
