# Generated by Django 4.2.4 on 2023-09-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0011_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='date',
            new_name='date_from',
        ),
        migrations.AddField(
            model_name='experience',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
