# Generated by Django 4.2.4 on 2023-09-09 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0030_alter_author_avatar_alter_author_cv'),
        ('provile', '0012_rename_date_experience_date_from_experience_date_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('media_url', models.URLField(verbose_name='Url')),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geology.author')),
            ],
            options={
                'verbose_name': 'MediaUrl',
                'verbose_name_plural': 'MediaUrls',
            },
        ),
    ]
