# Generated by Django 4.2.4 on 2023-09-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0016_alter_mediaurl_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaurl',
            name='name',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')], null=True, unique=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geology.author')),
        ),
    ]
