# Generated by Django 4.2.4 on 2023-09-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0017_alter_mediaurl_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaurl',
            name='name',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')], null=True),
        ),
    ]
