# Generated by Django 4.2.4 on 2023-09-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0019_alter_certificate_images_alter_experience_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaurl',
            name='name',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')]),
        ),
    ]
