# Generated by Django 4.2.4 on 2023-09-29 10:34

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0021_remove_contactprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='replay',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Replay'),
        ),
    ]
