# Generated by Django 4.2.4 on 2023-09-29 10:44

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0022_alter_contactprofile_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='message',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
