# Generated by Django 4.2.4 on 2023-09-29 11:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0025_alter_contactprofile_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='message',
            field=tinymce.models.HTMLField(verbose_name='Message'),
        ),
    ]
