# Generated by Django 4.2.4 on 2023-10-13 19:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0026_alter_contactprofile_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactprofile',
            name='replay',
            field=tinymce.models.HTMLField(default=1, verbose_name='Replay'),
            preserve_default=False,
        ),
    ]
