# Generated by Django 4.2.4 on 2023-10-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0027_alter_contactprofile_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactprofile',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
