# Generated by Django 4.2.4 on 2023-11-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provile', '0029_alter_contactprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaurl',
            name='name',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('LinkedIn', 'LinkedIn')], max_length=100),
        ),
    ]
