# Generated by Django 4.2.4 on 2023-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='repo_prograph',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
