# Generated by Django 4.2.4 on 2023-08-14 05:10

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0002_report_repo_prograph'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='repo_text',
            field=tinymce.models.HTMLField(default=2),
            preserve_default=False,
        ),
    ]
