# Generated by Django 4.2.4 on 2023-08-14 07:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0003_report_repo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='repo_prograph',
            field=tinymce.models.HTMLField(),
        ),
    ]
