# Generated by Django 4.2.4 on 2023-08-14 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0004_alter_report_repo_prograph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='repo_text',
        ),
    ]
