# Generated by Django 4.2.4 on 2023-08-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0006_gallery_remove_report_repo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(help_text='please write the title', max_length=200),
        ),
    ]
