# Generated by Django 4.2.4 on 2023-08-21 23:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0008_alter_report_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
