# Generated by Django 4.2.4 on 2023-08-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0009_alter_report_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='key_word',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
