# Generated by Django 4.2.4 on 2023-08-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0010_report_key_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(help_text='please write the title', max_length=200, unique=True),
        ),
    ]
