# Generated by Django 4.2.4 on 2023-09-03 13:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geology', '0015_alter_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user',
            field=models.OneToOneField(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
