# Generated by Django 4.2.4 on 2023-09-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0019_remove_report_user_id_author_report_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='fname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='gallery_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_provile_img/'),
        ),
        migrations.AddField(
            model_name='author',
            name='lname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='sname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='tname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='user_bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
