# Generated by Django 4.2.4 on 2023-09-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0020_remove_author_name_author_fname_author_gallery_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='user_bio',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
