# Generated by Django 4.2.4 on 2023-09-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0022_certificate_contactprofile_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
