# Generated by Django 4.2.4 on 2023-09-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0023_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['name'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallerys'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
