# Generated by Django 4.2.4 on 2023-09-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0024_alter_gallery_options_gallery_is_image_gallery_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='ContactProfile',
        ),
        migrations.RemoveField(
            model_name='author',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
