# Generated by Django 4.2.4 on 2023-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0025_delete_certificate_delete_contactprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/icon.jpg', null=True, upload_to='avatar/'),
        ),
    ]
