# Generated by Django 4.2.4 on 2023-09-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0026_alter_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, default='mediafiles/avatar/icon.jpg', null=True, upload_to='avatar/'),
        ),
    ]
