# Generated by Django 4.2.4 on 2023-09-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0029_alter_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/icon.jpg', null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='cv',
            field=models.FileField(blank=True, default='cv/hind.txt', null=True, upload_to='cv'),
        ),
    ]
