# Generated by Django 4.2.4 on 2023-09-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0030_alter_author_avatar_alter_author_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='intro_repo',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
