# Generated by Django 4.2.4 on 2023-09-15 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geology', '0032_report_edit_by_alter_report_intro_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='edit_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='intro_repo',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
