# Generated by Django 4.2.4 on 2023-09-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0036_author_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='degree',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('DA', "Diploma's degree"), ('BA', "Bachelor's degree"), ('MA', "Master's degree"), ('PHD', "Doctoral's degree"), ('AA', "Associate's degree"), ('Teaching Assistant', 'Teaching Assistant'), ('Assistant Lecturer', 'Assistant Lecturer'), ('Assistant Professor', 'Assistant Professor')], null=True),
        ),
    ]
