# Generated by Django 4.2.4 on 2023-09-20 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geology', '0037_alter_author_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rock_type', models.CharField(choices=[('Igneous Rocks', 'Igneous Rocks'), ('Sedimentary Rocks', 'Sedimentary Rocks'), ('Metamorphic Rocks', 'Metamorphic Rocks')])),
                ('name', models.CharField(help_text='please write the title', max_length=200, unique=True)),
                ('rock_img', models.ImageField(upload_to='Rocks/')),
                ('rock_details', tinymce.models.HTMLField()),
                ('key_word', models.CharField(max_length=400)),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geology.author')),
                ('edit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rock',
                'verbose_name_plural': 'Rocks',
            },
        ),
    ]
