# Generated by Django 4.2.4 on 2023-09-21 13:10

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0038_rock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='repo_prograph',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='rock',
            name='name',
            field=models.CharField(help_text='rock name..', max_length=200, unique=True),
        ),
    ]
