# Generated by Django 4.2.4 on 2023-09-21 16:24

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0039_alter_report_repo_prograph_alter_rock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='repo_prograph',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
