# Generated by Django 4.2.4 on 2023-09-22 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0040_alter_report_repo_prograph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'get_latest_by': 'pub_date'},
        ),
    ]
