# Generated by Django 4.2.4 on 2023-09-22 09:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0041_alter_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='repo_prograph',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
