# Generated by Django 4.2.4 on 2023-09-24 08:50

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0043_report_repo_prograph_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rock',
            name='rock_details',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
