# Generated by Django 4.2.4 on 2023-09-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0046_alter_rock_rock_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rock',
            options={'get_latest_by': 'pub_date'},
        ),
        migrations.AddField(
            model_name='rock',
            name='intro',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
