# Generated by Django 4.2.4 on 2023-09-26 08:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0047_alter_rock_options_rock_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Write your question', max_length=400, unique=True)),
                ('pub_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geology.author')),
            ],
            options={
                'get_latest_by': 'pub_date',
            },
        ),
    ]
