# Generated by Django 4.2.4 on 2023-09-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0048_faq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='Author',
            new_name='author',
        ),
    ]
