# Generated by Django 4.2.4 on 2023-09-26 09:38

from django.db import migrations, models
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0049_rename_author_faq_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
