# Generated by Django 4.2.4 on 2023-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0051_mineral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineral',
            name='other_classes',
        ),
        migrations.RemoveField(
            model_name='mineral',
            name='subgroups_sio',
        ),
        migrations.AlterField(
            model_name='mineral',
            name='name',
            field=models.CharField(help_text='mineral name..', max_length=200, unique=True),
        ),
    ]
