# Generated by Django 4.2.4 on 2023-10-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0052_remove_mineral_other_classes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
