# Generated by Django 4.2.4 on 2023-11-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0053_delete_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='cv',
            field=models.FileField(blank=True, default='cv/geologysd.txt', null=True, upload_to='cv'),
        ),
    ]
