# Generated by Django 4.2.4 on 2023-11-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0054_alter_author_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='degree',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('DA', "Diploma's degree"), ('BA', "Bachelor's degree"), ('MA', "Master's degree"), ('PHD', "Doctoral's degree"), ('AA', "Associate's degree"), ('Teaching Assistant', 'Teaching Assistant'), ('Assistant Lecturer', 'Assistant Lecturer'), ('Assistant Professor', 'Assistant Professor')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='classes',
            field=models.CharField(choices=[('Native Elements', 'Native Elements'), ('Sulfides', 'Sulfides'), ('Sulfates', 'Sulfates'), ('Halides', 'Halides'), ('Oxides', 'Oxides'), ('Carbinates', 'Carbinates'), ('Phosphates', 'Phosphates'), ('Silicates', 'Silicates'), ('Organic Minerals', 'Organic Minerals'), ('Other', 'Other')], max_length=200, verbose_name='Classes'),
        ),
        migrations.AlterField(
            model_name='rock',
            name='rock_type',
            field=models.CharField(choices=[('Igneous Rocks', 'Igneous Rocks'), ('Sedimentary Rocks', 'Sedimentary Rocks'), ('Metamorphic Rocks', 'Metamorphic Rocks')], max_length=100),
        ),
    ]
