# Generated by Django 4.2.4 on 2023-08-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dectionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dectionary',
            old_name='meaning',
            new_name='ar_meaning',
        ),
        migrations.AddField(
            model_name='dectionary',
            name='en_meaning',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
