# Generated by Django 4.2.4 on 2023-08-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dectionary', '0002_rename_meaning_dectionary_ar_meaning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dectionary',
            name='key_words',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
