# Generated by Django 4.2.4 on 2023-09-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0035_report_edit_date_alter_report_intro_repo'),
        ('dectionary', '0003_dectionary_key_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='dectionary',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geology.author'),
        ),
    ]
