# Generated by Django 4.2.4 on 2023-09-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geology', '0035_report_edit_date_alter_report_intro_repo'),
        ('dectionary', '0004_dectionary_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dectionary',
            name='word',
        ),
        migrations.AddField(
            model_name='dectionary',
            name='ar_word',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dectionary',
            name='en_word',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dectionary',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geology.author'),
            preserve_default=False,
        ),
    ]
