# Generated by Django 4.2.4 on 2023-09-19 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dectionary', '0005_remove_dectionary_word_dectionary_ar_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dectionary',
            name='edit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
